---
- name: launch boshlite box
  hosts: local
  gather_facts: false
  vars:
    keypair: juju
    #instance_type: m3.2xlarge
    instance_type: c3.2xlarge
    security_group: cf-pipeline-boshlite
    region: us-east-1
    secdesc: For cf-juju package exports
    # dmitry approved ami
    # image: ami-4cd75224
    # pre populated
    image: ami-6e1b8206
    spot_price: 0.125
  vars_files:
    - ./vars/run-vars.yml
  tasks:
  #@@ check and check again necessary due to bugs in ec2_group
  - name: check sec group
    local_action:
      module: ec2_group
      name: "{{ security_group }}"
      description: "{{ secdesc }}"
      state: present
      region: "{{ region }}"
    register: sec_group
    ignore_errors: true

  - name: security group
    local_action:
      module: ec2_group
      name: "{{ security_group }}"
      description: "{{ secdesc }}"
      region: "{{ region }}"
      state: present
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 10.0.0.0/0
      rules_egress:
        - proto: all
          from_port: all
          to_port: all
          cidr_ip: 10.0.0.0/0

  - name: Create keypair
    local_action:
      module: ec2_key
      name: "boshlite-cf-export"
      region: "{{ region }}"
      key_material: "{{ item }}"
      state: present
    with_file: "/home/ubuntu/.juju/ssh/juju_id_rsa.pub"

  - name: Launch boshlite instance
    local_action:
      module: ec2
      key_name: "boshlite-cf-export"
      group: "{{ security_group }}"
      instance_type: "{{ instance_type }}"
      # "{{ image }}"
      # ami-3a04df52
      # ami-ee529e86
      spot_price: "{{spot_price}}"
      image: "{{ image }}"
      wait: true
      state: present
      region: "{{ region }}"
      id: "boshlite-cf-export-{{instance_id}}"
      volumes:
        - device_name: /dev/sda1
          volume_size: 50
          delete_on_termination: true
    register: ec2

  - name: Add bl instance to host group
    local_action: add_host hostname={{ item.public_ip }} groupname=blbox
    with_items: ec2.instances

  - name: Wait for SSH to come up
    local_action:
      module: wait_for
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 20
      timeout: 960
      state: started
    with_items: ec2.instances

- include: boshlite.yml
